spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teste_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
